name: Python bindings
on: [push, pull_request]

env:
  CIBW_ENVIRONMENT_WINDOWS: PATH="$PATH;C:\\Boost\\bin" LIB="$LIB;C:\\Boost\\lib" INCLUDE="C:\\Boost\\include" VSCMD_ARG_TGT_ARCH=""
  CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.14

  CIBW_BEFORE_ALL: bash {package}/bindings/python/tools/install_boost.sh {package}
  CIBW_BEFORE_BUILD: bash {package}/bindings/python/tools/install_boost_python.sh {package}
  CIBW_TEST_COMMAND: python {package}/bindings/python/test/test.py -b

  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014

  CIBW_SKIP: cp27-* pp*

jobs:
  build:
    name: Building and testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Cache Boost on Windows
      if: runner.os == 'Windows'
      uses: actions/cache@v2
      with:
        path: C:\\Boost
        key: windows-boost-173

    - name: Cache Boost on macOS
      if: runner.os == 'macOS'
      uses: actions/cache@v2
      with:
        path: |
          /usr/local/Cellar/boost-build/1.73.0
          /usr/local/Cellar/boost/1.73.0
          /usr/local/opt/boost
          /usr/local/include/boost
          /usr/local/lib/libboost_*
          /usr/local/share/boost-build
          /usr/local/bin/b2
        key: macos-boost-173

    - name: Install Visual C++ Developer Command Prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel

    - name: Build and test wheels
      run: python -m cibuildwheel

    - name: Upload artifacts to storage
      if: success() || failure()
      uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl
